POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMjMiLCJpZCI6IjVkZTUzODE3OTcyODc1NTZjZWFkMGIxOCIsImlhdCI6MTU3NTMwMzIwOX0.-BVEGeRYXd7yIg-1qbY7mKTtOpK0u9fz5Gm0IKOarjs

{
    "title": "Is works with a TOKEN MIDDLEWARE?",
    "author": "foo",
    "url":"www.url.fi",
    "likes": 2,
    "userId": "5de5381797287556cead0b18"
}